DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS questions;

CREATE TABLE questions (
	id INTEGER AUTO_INCREMENT NOT NULL,
	description VARCHAR(500) NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	begin_date TIMESTAMP NOT NULL,
	end_date TIMESTAMP NOT NULL,
	CONSTRAINT questions_pk PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8, ENGINE=INNODB;

CREATE TABLE votes (
	id VARCHAR(50) NOT NULL,
	question_id INTEGER NOT NULL,
	vote_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT vote_unique UNIQUE(id,question_id),
	CONSTRAINT votes_pk PRIMARY KEY(id,question_id),
	CONSTRAINT votes_questions_fk FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8, ENGINE=INNODB;

CREATE TABLE answers (
	name VARCHAR(5) NOT NULL,
	description VARCHAR(200) NOT NULL,
	question_id INTEGER NOT NULL,
	votes INTEGER DEFAULT 0 NOT NULL,
	CONSTRAINT answers_pk PRIMARY KEY(name,question_id),
	CONSTRAINT positive_votes CHECK (votes >= 0),
	CONSTRAINT answers_questions_fk FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8, ENGINE=INNODB;